/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/skeleton/pirate.gltf --transform -t
Files: public/models/skeleton/pirate.gltf [95.7KB] > /home/ark/Documentos/TonussiLabs/Web/lucastonussi/pirate-transformed.glb [950.47KB] (-893%)
Author: FireGoat (https://sketchfab.com/FireGoat)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/skeleton-pirate-the-captin-65cbe69004924bbc940cd74276ba90fb
Title: Skeleton Pirate " The Captin "
*/

import { useAnimations, useGLTF } from '@react-three/drei'
import { useGraph } from '@react-three/fiber'
import { useEffect, useMemo, useRef } from 'react'
import * as THREE from 'three'
import { type GLTF, SkeletonUtils } from 'three-stdlib'

type ActionName = 'Armature|DefaultSkeletonPose' | 'Armature|RunningAtPlayerAnimation'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Object_9: THREE.SkinnedMesh
    Object_10: THREE.SkinnedMesh
    _rootJoint: THREE.Bone
  }
  materials: {
    Skeleton: THREE.MeshStandardMaterial
    SkeletonGear: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

function Pirate({
  animation,
  scale,
  position,
}: {
  animation: number
  scale: number
  position: THREE.Vector3
}) {
  const group = useRef<THREE.Group>(null!)
  const { scene, animations } = useGLTF('/models/skeleton/pirate.glb')
  const clone = useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as unknown as GLTFResult
  const { actions, names } = useAnimations(animations, group)

  useEffect(() => {
    actions?.[names[animation]]?.reset().fadeIn(0.5).play()
    return () => {
      actions?.[names[animation]]?.fadeOut(0.5)
    }
  }, [animation])

  return (
    <group name="player" ref={group} dispose={null}>
      <group name="Sketchfab_Scene">
        <primitive object={nodes._rootJoint} scale={scale} position={position} />
        <skinnedMesh
          name="Object_9"
          geometry={nodes.Object_9.geometry}
          material={materials.Skeleton}
          skeleton={nodes.Object_9.skeleton}
          scale={scale}
          castShadow
          receiveShadow
        />
        <skinnedMesh
          name="Object_10"
          geometry={nodes.Object_10.geometry}
          material={materials.SkeletonGear}
          skeleton={nodes.Object_10.skeleton}
          scale={scale}
          castShadow
          receiveShadow
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/skeleton/pirate.glb')

export default Pirate
